import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { Hw2GeneratedModule, Hw2GeneratedSharedModule } from './generated/module.js';
import { Hw2Validator, registerValidationChecks } from './hw-2-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type Hw2AddedServices = {
    validation: {
        Hw2Validator: Hw2Validator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type Hw2Services = LangiumServices & Hw2AddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const Hw2Module: Module<Hw2Services, PartialLangiumServices & Hw2AddedServices> = {
    validation: {
        Hw2Validator: () => new Hw2Validator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createHw2Services(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Hw2: Hw2Services
} {
    const shared = inject(
        createDefaultSharedModule(context),
        Hw2GeneratedSharedModule
    );
    const Hw2 = inject(
        createDefaultModule({ shared }),
        Hw2GeneratedModule,
        Hw2Module
    );
    shared.ServiceRegistry.register(Hw2);
    registerValidationChecks(Hw2);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Hw2 };
}
