name: Continuous Integration
on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Gradlew executable
        run: chmod +x ./gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check phase 1
        run: ./gradlew build -PhomeworkStage=1
      - name: Check phase 2
        run: ./gradlew build -PhomeworkStage=2
      - name: Check phase 3
        run: ./gradlew build -PhomeworkStage=3
      - name: Check phase 4
        run: ./gradlew build -PhomeworkStage=4
